config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/about'

    resources :clinics do
      member do
      post :create_doctor
      delete :destroy_doctor
    end
      resources :patients do
        collection do 
          get 'search'
        end
        member do
          post :create_doctor
          delete :destroy_doctor
          patch :wait_patient
          patch :to_doctor_patient
          patch :to_xray_patient
          patch :to_surgery_patient
          patch :to_pay_bill_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_many :patient_medications
  has_many :patients, through: :patient_medications

  validates :name, presence: true


  def has_generic?
    if self.generic_option == true
      "yes"
    else
      "no"
    end
  end


end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

  def index
    @medications = if !params[:q].blank?
      Medication.where("name LIKE ? OR company LIKE ? OR adverse_reactions LIKE ? OR generic_option LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
    @medications = Medication.all
    end
  end

  def show
    @medication = Medication.find params[:id]
    @patients = @medication.patients
  end

    # @clinic = Clinic.find params[:clinic_id]
    # @patient = @clinic.patients.find params[:patient_id]
    # @medication = @patient.medications.new


  def new
    @medication = Medication.new
    @patients = Patient.all
  end

  def create
    @patients = Patient.all
    @medication = Medication.create medication_params
    if @medication.save
      flash[:notice] = "Medication was successfully saved."
      redirect_to medications_path
    else
      flash[:alert] = "Medication was NOT successfully saved."
      render :new
    end

  end

  def edit
    @medication = Medication.find params[:id]
    @patients = Patient.all
  end

  def update
    @patients = Patient.all
    @medication = Medication.find params[:id]
    if @medication.update medication_params
      flash[:notice] = "Medication was successfully updated."
      redirect_to medication_path(@medication)
    else
      flash[:alert] = "Medication was NOT successfully updated."
      render :edit
    end
  end

  def destroy
    @medication = Medication.find params[:id]
    @medication.delete
    redirect_to medications_path
  end


private
  def medication_params
    params.require(:medication).permit(
      :name,
      :company,
      :adverse_reactions,
      :generic_option,
      patient_ids: []
      )
  end

  def set_patient
    @patient = Patient.find params[:id]
  end

end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.haml
= form_for([@medication]) do |f|
  - if @medication.errors.any?
    - @medication.errors.full_messages.each do |message|
      = message
      %br
.list-group-item.text-center
  =form_for [@medication] do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control name_field"
      %span.error_name
        Medication name required
    .form-group
      = f.label :company
      = f.text_field :company, class: "form-control"
    .form-group
      = f.label :adverse_reactions
      = f.text_area :adverse_reactions, class: "form-control"
    .list-group-item
      = f.label :generic_option
      = f.radio_button(:generic_option, 1)
      = f.label(:generic_option, "yes")
      = f.radio_button(:generic_option, 0)
      = f.label(:generic_option, "no")
    %br
    .list-group-item
      %strong
        = "Patients using:"
      .text-left
        .checkbox
          - @patients.each do |patient|
            %label
              = check_box_tag 'medication[patient_ids][]', patient.id, @medication.patients.include?(patient)
              = patient.last_name + ', ' + patient.first_name
            %br
    %br
    = f.submit "Submit", class: "btn btn-primary submit"

app/views/medications/edit.html.haml
.col-md-12
  .col-md-6.col-md-offset-3
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              = "Edit #{@medication.name}"
        = link_to "Cancel", medication_path(@medication)

    = render 'form'

app/views/medications/index.html.haml
= form_tag medications_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Medications"
    .input-group-btn
      %button.btn.btn-default{:style => "width:40px;"}
        %i.glyphicon.glyphicon-search
.col-md-12
  .col-md-6.col-md-offset-3
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              Medications
          = link_to "Add New Medication", new_medication_path
.row
- x = 0
- y = 1
%ul{class: "medication_list"}     
  - @medications.each_slice(10) do |row|
    %li{class: "section_#{x+1}"}
      - x = x + 1
      - row.each do |medication|
        .col-md-3
          .list-group-item.text-center
            = link_to medication[:name], medication_path(medication)
            %br
            = medication[:company]
          %br
      %br 
    %br
.col-md-12.text-center
  %ul{class: "link_list" }
    - x.times do
      %li{class: "link_#{y}"}
        %a{class: "link_#{y}", med_num: y} 
          = "page #{y}"
        = "|"
      - y += 1
%br
%br

app/views/medications/new.html.haml
.col-md-12
  .col-md-6.col-md-offset-3
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              New Medication
        = link_to "Cancel", clinics_path
    =render 'form'

app/views/medications/show.html.haml
.col-md-12
  .col-md-6.col-md-offset-3
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              = @medication.name
        = link_to "Edit Medication", edit_medication_path(@medication)
        |
        = link_to "Delete Medication",  medication_path(@medication), method: :delete
    .list-group-item
      %strong Medication Name:
      = @medication.name
      %br/
      %strong Company:
      = @medication.company
      %br/
      %strong Adverse Reactions:
      = @medication.adverse_reactions
      %br/
      %strong Generic Options Available:
      = @medication.has_generic?
      %br/
    %br
    .list-group-item
      .text-center
        %strong Patient Users:
        %br
        %br
        %ul
          - @patients.each do |patient|
            %li
              = patient.last_name
              = patient.first_name
              %br