config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/about'

    resources :clinics do
      member do
      post :create_doctor
      delete :destroy_doctor
    end
      resources :patients do
        collection do 
          get 'search'
        end
        member do
          post :create_doctor
          delete :destroy_doctor
          patch :wait_patient
          patch :to_doctor_patient
          patch :to_xray_patient
          patch :to_surgery_patient
          patch :to_pay_bill_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :clinic
  has_many :patient_medications
  has_many :medications, through: :patient_medications
  has_many :doctors, as: :doctorable

  BLOOD_TYPE_OPTIONS = [
    ["O-", "O-"],
    ["O+", "O+"],
    ["A-", "A-"],
    ["A+", "A+"],
    ["B-", "B-"],
    ["B+", "B+"],
    ["AB-", "AB-"],
    ["AB+", "AB+"],
  ]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :gender, presence: true
  validates :blood_type, presence: true
  validate :at_least_10
  
  def at_least_10
    if self.date_of_birth
        errors.add(:date_of_birth, 'Error. Patient must be at least 10 years old') if self.date_of_birth > 10.years.ago.to_date  
    end
  end

  include Workflow
  workflow do
    state :waiting_room do
      event :to_doctor, transitions_to: :doctor_checkup
      event :to_xray, transitions_to: :xray
      event :to_surgery, transitions_to: :surgery
      event :leave, transitions_to: :left
    end
    
    state :doctor_checkup do
      event :to_xray, transitions_to: :xray
      event :to_surgery, transitions_to: :surgery
      event :to_pay_bill, transitions_to: :pay_bill
    end

    state :xray do
      event :to_doctor, transitions_to: :doctor_checkup
      event :to_surgery, transitions_to: :surgery
      event :to_pay_bill, transitions_to: :pay_bill
    end

    state :surgery do
      event :to_doctor, transitions_to: :doctor_checkup
      event :to_xray, transitions_to: :xray
      event :to_pay_bill, transitions_to: :pay_bill
    end

    state :pay_bill do
      event :leave, transitions_to: :left
    end

    state :left do
      event :wait, transitions_to: :waiting_room
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [
    :show,
    :edit,
    :update,
    :destroy,
    :wait_patient
  ]

  def index
    set_clinic
    @patients = if !params[:q].blank?
      @clinic.patients.where("first_name LIKE ? OR last_name LIKE ? OR date_of_birth LIKE ? OR description LIKE ? OR gender LIKE ? OR blood_type LIKE ? OR workflow_state LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @clinic.patients
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
   @clinic = Clinic.find params[:clinic_id]
   @patient = Patient.find params[:id]
   @medications = @patient.medications
   @doctor = Doctor.new
   @doctors = if !params[:q].blank?
    @patient.doctors.where("doctor_name LIKE ?", "%#{params[:q]}%")
   else
    @patient.doctors
    end
  end


  def new
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.new
    @medications = Medication.all
  end

  def create
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.create patient_params
    @medications = Medication.all
    if @patient.save
      flash[:notice] = 'Patient info was successfully saved.'
      redirect_to clinic_path(@clinic)
    else
      flash[:alert] = 'Patient info was NOT successfully saved.'
      render :new
    end
  end

  def edit
    @clinic = Clinic.find params[:clinic_id]
    @medications = Medication.all
    @patient = @clinic.patients.find params[:id]
  end

  def update
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @medications = Medication.all
    if @patient.update_attributes patient_params
      flash[:notice] = 'Patient info was successfully updated.'
      redirect_to clinic_path(@clinic)
    else
      flash[:alert] = 'Patient info was NOT successfully updated.'
      render :edit
    end
  end

  def destroy
    @patient = Patient.find params[:id]
    @clinic = Clinic.find params[:clinic_id]
    if @patient.destroy
      flash[:notice] = 'Patient info was successfully deleted.'
      redirect_to clinic_path(@clinic)
    else
      flash[:alert] = 'Patient info was NOT successfully deleted.'
    end
  end

  def create_doctor
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id] 
    @doctor = @patient.doctors.create doctor_params
    redirect_to clinic_patient_path(@clinic, @patient)
  end

  def destroy_doctor
    @doctor = Doctor.find params[:id]
    @doctor.destroy
    redirect_to clinic_patient_path(@doctor.doctorable.clinic, @doctor.doctorable)
  end

  def wait_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.wait!
    respond_to do |format|
      format.js
    end
  end

  def to_doctor_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_doctor!
    respond_to do |format|
      format.js
    end
  end

  def to_xray_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_xray!
    respond_to do |format|
      format.js
    end
  end

  def to_surgery_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_surgery!
    respond_to do |format|
      format.js
    end
  end

  def to_pay_bill_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_pay_bill!
    respond_to do |format|
      format.js
    end
  end

  def leave_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.leave!
    respond_to do |format|
      format.js
    end
  end

  def search
    @clinic = Clinic.find params[:clinic_id]
    if !params[:q].blank? 
      @patients = @clinic.patients.where("first_name LIKE ? OR last_name LIKE ? OR date_of_birth LIKE ? OR description LIKE ? OR gender LIKE ? OR blood_type LIKE ? OR workflow_state LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @patients = @clinic.patients
    end
    respond_to do |format|
      format.js
      format.html
    end
    puts params[:_]
  end

private
  def patient_params
    params.require(:patient).permit(
        :first_name,
        :last_name,
        :date_of_birth,
        :description,
        :gender,
        :blood_type,
        medication_ids: []
      ) 
  end

  def set_clinic
    @clinic = Clinic.find(params[:clinic_id])
  end

  def set_patient
    @patient = Patient.find params[:id]
  end

  def doctor_params
  params.require(:doctor).permit(
    :doctor_name
    )
  end

end

app/helpers/patients_helper.rb
module PatientsHelper

  def workflow_state_helper(patient)
    if patient.current_state == "waiting_room"
      "Patient is in waiting room."
    elsif patient.workflow_state == "doctor_checkup"
      "Patient is with the doctor."
    elsif patient.workflow_state == "xray"
      "Patient is in xray."
    elsif patient.workflow_state == "surgery"
      "Patient is in surgery."
    elsif patient.workflow_state == "pay_bill"
      "Patient is paying bill."
    elsif patient.workflow_state == "left"
      "Patient has left."
    end
  end

  def patient_state_links(patient, clinic)
    patient_state_links_array = []
    waiting_room_links = [
      (link_to "To Doctor", 'javascript:void(0);', class: 'to-doctor', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To X-ray", 'javascript:void(0);', class: 'to-xray', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To Surgery", 'javascript:void(0);', class: 'to-surgery', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "Leave", 'javascript:void(0);', class: 'leave', patient_id: patient.id, clinic_id: clinic.id)
    ]
    doctor_checkup_links = [
      (link_to "To X-ray", 'javascript:void(0);', class: 'to-xray', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To Surgery", 'javascript:void(0);', class: 'to-surgery', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To Pay Bill", 'javscript:void(0);', class: 'to-pay-bill', patient_id: patient.id, clinic_id: clinic.id)
    ]
    xray_links = [
      (link_to "To Doctor", 'javscript:void(0);', class: 'to-doctor', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To Surgery", 'javascript:void(0);', class: 'to-surgery', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To Pay Bill", 'javscript:void(0);', class: 'to-pay-bill', patient_id: patient.id, clinic_id: clinic.id)
    ]
    surgery_links = [
      (link_to "To Doctor", 'javscript:void(0);', class: 'to-doctor', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To X-ray", 'javascript:void(0);', class: 'to-xray', patient_id: patient.id, clinic_id: clinic.id),
      (link_to "To Pay Bill", 'javscript:void(0);', class: 'to-pay-bill', patient_id: patient.id, clinic_id: clinic.id)
    ]
    pay_bill_links = [
      (link_to "Leave", 'javascript:void(0);', class: 'to-leave', patient_id: patient.id, clinic_id: clinic.id)
    ]
    left_links = [
      (link_to "Back in to Waiting Room", 'javascript:void(0);', class: 'to-waiting-room', patient_id: patient.id, clinic_id: clinic.id)
    ]
    if patient.waiting_room?
      patient_state_links_array.push(waiting_room_links)
      return patient_state_links_array.join(' | ').html_safe
    elsif patient.doctor_checkup?
      patient_state_links_array.push(doctor_checkup_links)
      return patient_state_links_array.join(' | ').html_safe
    elsif patient.xray?
      patient_state_links_array.push(xray_links)
      return patient_state_links_array.join(' | ').html_safe
    elsif patient.surgery?
      patient_state_links_array.push(surgery_links)
      return patient_state_links_array.join(' | ').html_safe
    elsif patient.pay_bill?
      patient_state_links_array.push(pay_bill_links)
      return patient_state_links_array.join(' | ').html_safe
    elsif patient.left?
      patient_state_links_array.push(left_links)
      return patient_state_links_array.join(' | ').html_safe
    end
  end
end

app/views/patients/_form.html.haml
= form_for([@clinic, @patient]) do |f|
  - if @patient.errors.any?
    - @patient.errors.full_messages.each do |message|
      = message
      %br
.text-center
  = form_for [@clinic, @patient] do |f|
    .form-group
      %strong= f.label :first_name
      = f.text_field :first_name, class: "form-control name_field"
      %span.error_first_name
        First name required
    .form-group
      %strong= f.label :last_name
      = f.text_field :last_name, class: "form-control name_field"
      %span.error_last_name
        Last name required
    .form-group
      %strong= f.label :date_of_birth
      = f.date_field :date_of_birth, :start_year => Date.today.year - 110, :end_year => Date.today.year, class: "form-control"
    .form-group
      %strong= f.label :description
      = f.text_field :description, class: "form-control"
    %br
      %strong= f.label :gender
      = f.radio_button(:gender, "male")
      = f.label(:gender, "male")
      = f.radio_button(:gender, "female")
      = f.label(:gender, "female")
    %br
      %strong= f.label :blood_type
      = f.select :blood_type, options_for_select(Patient::BLOOD_TYPE_OPTIONS, f.object.blood_type), include_blank: "---Select---"
    .text-left
      .checkbox
        - @medications.each do |medication|
          %label
            = check_box_tag 'patient[medication_ids][]', medication.id, @patient.medications.include?(medication)
            = medication.name
    %br/
    = f.submit "Submit", class: "btn btn-primary submit"

app/views/patients/_index.html.haml
.index-data
  - x = 0
  - y = 1
  %ul{class: "patient_list"}     
    - @patients.each_slice(10) do |row|
      %li{class: "section_#{x+1}"}
        - x = x + 1
        - row.each do |patient|
          .col-md-3
            .list-group-item
              = link_to (patient[:last_name] + ', ' + patient[:first_name]), clinic_patient_path(@clinic, patient)
            %br
        %br 
      %br
  .col-md-12.text-center
    %ul{class: "link_list" }
      - x.times do
        %li{class: "link_#{y}"}
          %a{class: "link_#{y}", patient_num: y} 
            = "page #{y}"
          = "|"
        - y += 1
  %br
  %br

app/views/patients/_patient_workflow_state.html.haml
.container.content
  = "Patient Status: "
  = workflow_state_helper(@patient)
  %br
  = patient_state_links(@patient, @clinic)
  %br

app/views/patients/edit.html.erb
<h1>Edit Patient Info</h1>
<%= render 'form' %>

app/views/patients/index.html.haml
.col-md-4
  .input-group
    = text_field_tag 'srch-term', '', class: "form-control", id: "srch-term", placeholder: "Search Patients"
    .input-group-btn
      %button.btn.btn-default.search-submit{:style => "width:40px;", clinic_id: @clinic.id}
        %i.glyphicon.glyphicon-search
.col-md-12
  .col-md-6.col-md-offset-3
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              = "Patients at Clinic: #{@clinic.name}"
          = link_to "Return to Clinic", clinic_path(@clinic)

/ %ul
/   - @patients.each do |patient|
/     .col-md-4.text-center
/       .list-group-item
/         %li
/           = link_to patient.first_name + ' ' + patient.last_name, clinic_patient_path(@clinic, patient)
/           = '|'
/           = workflow_state_helper(patient)
/         %br
/       %br  

.row
.index-data
  - x = 0
  - y = 1
  %ul{class: "patient_list"}     
    - @patients.each_slice(10) do |row|
      %li{class: "section_#{x+1}"}
        - x = x + 1
        - row.each do |patient|
          .col-md-3
            .list-group-item
              = link_to (patient[:last_name] + ', ' + patient[:first_name]), clinic_patient_path(@clinic, patient)
            %br
        %br 
      %br
  .col-md-12.text-center
    %ul{class: "link_list" }
      - x.times do
        %li{class: "link_#{y}"}
          %a{class: "link_#{y}", patient_num: y} 
            = "page #{y}"
          = "|"
        - y += 1
  %br
  %br



/ %h1 Patients
/ %br/
/ = link_to "Create New Patient Information", new_patient_path
/ %br/
/ %ul
/   - @patients.each do |patient|
/     %li
/       %strong Patient Name:
/       = link_to patient.last_name + ", " + patient.first_name, patient_path(patient)
/       %br/
/       %strong DOB:
/       = patient.date_of_birth
/       %br/
/       %strong Description:
/       = patient.description
/       %br/
/       %strong Gender:
/       = patient.gender
/       %br/
/       %strong Blood Type:
/       = patient.blood_type
/       %br/
/       = link_to "Edit Patient", edit_patient_path(patient)
/       |
/       \#{link_to "Delete Patient", patient_path(patient), method: :delete}
/     %br/
/ = link_to "Return to Main", root_path

app/views/patients/leave_patient.js.haml
$("div.content").html("#{j(render 'patient_workflow_state')}")

app/views/patients/new.html.haml
.col-md-12
  .col-md-6.col-md-offset-3
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              Enter Patient Information
        = link_to "Cancel", clinic_path(@clinic)

    = render 'form'
    = link_to 'Cancel', clinic_path(@clinic)

app/views/patients/search.js.haml
$(".index-data").html("#{j(render 'index')}")

app/views/patients/show.html.haml
.col-md-6.col-md-offset-3
  .jumbotron
    .text-center
      %strong
        %h3
          %u
            Patient:
            = @patient.last_name + ", " + @patient.first_name
      = render 'patients/patient_workflow_state'
      %br
      = link_to "Edit Patient/Medication", edit_clinic_patient_path(@clinic, @patient)
      |
      = link_to "Delete Patient", clinic_patient_path(@clinic, @patient), method: :delete
      %br
      = link_to "Return to Clinic", clinic_path(@clinic)
      |
      = link_to "Return to Main", root_path
      %br
  %p{class: "text-left"}
    .list-group-item
      %strong DOB:
      = @patient.date_of_birth
      %br/
      %strong Symptoms:
      = @patient.description
      %br/
      %strong Gender:
      = @patient.gender
      %br/
      %strong Blood Type:
      = @patient.blood_type
      %br/
      
    %br/
    .list-group-item
      .text-center
        .h4
          %strong Patient Medications:
        %ul
          - @medications.each do |medication|
            %li
              = link_to medication.name, medication_path(medication)
            %br  
    %br
    .list-group-item
      .text-center
        .h4
          %strong Patient Doctor(s) Name:
        = form_tag clinic_patient_path(@clinic, @patient), method: :get, class: "navbar-form", role: "search" do
          .input-group
            = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Doctors"
            .input-group-btn
              %button.btn.btn-default{:style => "width:40px;"}
                %i.glyphicon.glyphicon-search
      %br          
      %ul
        - @doctors.each do |doctor|
          %li
            = doctor.doctor_name
            = link_to "Remove Doctor", destroy_doctor_clinic_patient_path(@patient, doctor), method: :delete
          %br

      .text-center
        = form_for @doctor, url: create_doctor_clinic_patient_path(@clinic, @patient) do |f|
          .form_group
            = f.label :doctor_name
            = f.text_area :doctor_name, class: "form-control"
            %br
            = f.submit "Add Doctor", class: "btn btn-primary"

app/views/patients/to_doctor_patient.js.haml
$("div.content").html("#{j(render 'patient_workflow_state')}")

app/views/patients/to_pay_bill_patient.js.haml
$("div.content").html("#{j(render 'patient_workflow_state')}")

app/views/patients/to_surgery_patient.js.haml
$("div.content").html("#{j(render 'patient_workflow_state')}")

app/views/patients/to_xray_patient.js.haml
$("div.content").html("#{j(render 'patient_workflow_state')}")

app/views/patients/wait_patient.html.haml
$("div.content").html("#{j(render 'patient_workflow_state')}")